FROM oven/bun:1.4.0 AS bun

FROM mcr.microsoft.com/playwright:v1.62.1-noble

COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun

WORKDIR /work

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --ignore-scripts

COPY . .

ENV CI=1

CMD ["bun", "run", "test:ci"]
