export { default as Arrow } from "./Arrow";
export { default as Email } from "./Email";
export { default as Facebook } from "./Facebook";
export { default as Instagram } from "./Instagram";
export { default as Linkedin } from "./Linkedin";
export { default as Logo } from "./Logo";
export { default as Pause } from "./Pause";
export { default as Play } from "./Play";
export { default as Youtube } from "./Youtube";
