#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# The shared wizard template defines RED for scripts that need an error color.
: "$RED"

copy_secret_to_clipboard() {
  local value="$1"
  if command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$value" | pbcopy
  elif command -v wl-copy >/dev/null 2>&1; then
    printf '%s' "$value" | wl-copy
  elif command -v xclip >/dev/null 2>&1; then
    printf '%s' "$value" | xclip -selection clipboard
  elif command -v clip.exe >/dev/null 2>&1; then
    printf '%s' "$value" | clip.exe
  else
    return 1
  fi
}

clear_clipboard() {
  copy_secret_to_clipboard "" || true
}

trigger_webhook() {
  local url="$1"
  printf 'url = "%s"\nrequest = "POST"\nsilent\nshow-error\nfail\n' "$url" |
    curl --config - >/dev/null
}

trap clear_clipboard EXIT

banner "Carolyn + Sarabeth Contentful build webhooks"

stage "Collect webhook URLs and space IDs"
say "Deploy the reviewed Carolyn stack update and ensure Sarabeth's existing hosting stack is current before continuing."
warn "This wizard does not deploy infrastructure. The two webhook URLs are sensitive build triggers."
step "Retrieve Carolyn's ContentfulWebhookUrl output from CarolynPortfolioHostingStack in us-west-2."
note "aws cloudformation describe-stacks --stack-name CarolynPortfolioHostingStack --region us-west-2 --query \"Stacks[0].Outputs[?OutputKey=='ContentfulWebhookUrl'].OutputValue | [0]\" --output text"
ask_secret CAROLYN_WEBHOOK_URL "Paste Carolyn's ContentfulWebhookUrl:"
step "Retrieve Sarabeth's ContentfulWebhookUrl output from sarabeth-amplify-hosting in us-west-2."
note "aws cloudformation describe-stacks --stack-name sarabeth-amplify-hosting --region us-west-2 --query \"Stacks[0].Outputs[?OutputKey=='ContentfulWebhookUrl'].OutputValue | [0]\" --output text"
ask_secret SARABETH_WEBHOOK_URL "Paste Sarabeth's ContentfulWebhookUrl:"
ask CAROLYN_CONTENTFUL_SPACE_ID "Carolyn Contentful space ID:"
ask SARABETH_CONTENTFUL_SPACE_ID "Sarabeth Contentful space ID:"

if [[ -z "$CAROLYN_WEBHOOK_URL" || -z "$SARABETH_WEBHOOK_URL" ]]; then
  warn "Both Amplify webhook URLs are required."
  exit 1
fi
if [[ "$CAROLYN_WEBHOOK_URL" == "$SARABETH_WEBHOOK_URL" ]]; then
  warn "The sites must use distinct Amplify webhook URLs."
  exit 1
fi
for webhook_url in "$CAROLYN_WEBHOOK_URL" "$SARABETH_WEBHOOK_URL"; do
  if [[ ! "$webhook_url" =~ ^https:// ]]; then
    warn "Amplify webhook URLs must use HTTPS."
    exit 1
  fi
done
for space_id in "$CAROLYN_CONTENTFUL_SPACE_ID" "$SARABETH_CONTENTFUL_SPACE_ID"; do
  if [[ ! "$space_id" =~ ^[A-Za-z0-9_-]+$ ]]; then
    warn "Contentful space IDs may contain only letters, numbers, underscores, and hyphens."
    exit 1
  fi
done

stage "Configure Carolyn in Contentful"
say "Create a webhook that rebuilds only Carolyn from Carolyn's production content space."
open_url "https://app.contentful.com/spaces/${CAROLYN_CONTENTFUL_SPACE_ID}/settings/webhooks"
step "Edit 'Carolyn production Amplify rebuild' if it exists; otherwise choose Add webhook and use that name."
if copy_secret_to_clipboard "$CAROLYN_WEBHOOK_URL"; then
  step "Set the request method to POST and paste Carolyn's webhook URL from your clipboard."
else
  warn "Clipboard access is unavailable; retrieve Carolyn's ContentfulWebhookUrl again without printing it into shared logs."
fi
step "Select only Entry publish, Entry unpublish, Asset publish, and Asset unpublish."
step "Add an environment filter: Environment ID equals master."
step "Leave the webhook active, save it, and confirm its URL is masked in Contentful."
pause "Carolyn's webhook is saved?"

stage "Configure Sarabeth in Contentful"
say "Create a separate webhook in Sarabeth's production content space."
open_url "https://app.contentful.com/spaces/${SARABETH_CONTENTFUL_SPACE_ID}/settings/webhooks"
step "Edit 'Sarabeth production Amplify rebuild' if it exists; otherwise choose Add webhook and use that name."
if copy_secret_to_clipboard "$SARABETH_WEBHOOK_URL"; then
  step "Set the request method to POST and paste Sarabeth's webhook URL from your clipboard."
else
  warn "Clipboard access is unavailable; retrieve Sarabeth's ContentfulWebhookUrl again without printing it into shared logs."
fi
step "Select only Entry publish, Entry unpublish, Asset publish, and Asset unpublish."
step "Add an environment filter: Environment ID equals master."
step "Leave the webhook active, save it, and confirm its URL is masked in Contentful."
pause "Sarabeth's webhook is saved?"

stage "Optional controlled verification"
warn "Each test below starts a real production Amplify build and deploy. It does not require a GitHub workflow dispatch."
if confirm "Trigger one Carolyn production build now?"; then
  trigger_webhook "$CAROLYN_WEBHOOK_URL"
  open_url "https://us-west-2.console.aws.amazon.com/amplify/apps"
  pause "Confirm a Carolyn webhook build appeared, then press Enter."
else
  SKIPPED+=("Carolyn webhook production-build verification")
fi
if confirm "Trigger one Sarabeth production build now?"; then
  trigger_webhook "$SARABETH_WEBHOOK_URL"
  open_url "https://us-west-2.console.aws.amazon.com/amplify/apps"
  pause "Confirm a Sarabeth webhook build appeared, then press Enter."
else
  SKIPPED+=("Sarabeth webhook production-build verification")
fi
clear_clipboard

finish
