/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AreyouRouteImport } from './routes/areyou'
import { Route as IndexRouteImport } from './routes/index'

const AreyouRoute = AreyouRouteImport.update({
  id: '/areyou',
  path: '/areyou',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areyou': typeof AreyouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areyou': typeof AreyouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areyou': typeof AreyouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/areyou'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areyou'
  id: '__root__' | '/' | '/areyou'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreyouRoute: typeof AreyouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/areyou': {
      id: '/areyou'
      path: '/areyou'
      fullPath: '/areyou'
      preLoaderRoute: typeof AreyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreyouRoute: AreyouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
