/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEmailRouteImport } from './routes/api.email'
import { Route as _tsrStaticServerFnCacheFilenameRouteImport } from './routes/[_]_tsr.staticServerFnCache.$filename'

const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailRoute = ApiEmailRouteImport.update({
  id: '/api/email',
  path: '/api/email',
  getParentRoute: () => rootRouteImport,
} as any)
const _tsrStaticServerFnCacheFilenameRoute =
  _tsrStaticServerFnCacheFilenameRouteImport.update({
    id: '/__tsr/staticServerFnCache/$filename',
    path: '/__tsr/staticServerFnCache/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRoute
  '/lessons': typeof LessonsRoute
  '/media': typeof MediaRoute
  '/api/email': typeof ApiEmailRoute
  '/__tsr/staticServerFnCache/$filename': typeof _tsrStaticServerFnCacheFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRoute
  '/lessons': typeof LessonsRoute
  '/media': typeof MediaRoute
  '/api/email': typeof ApiEmailRoute
  '/__tsr/staticServerFnCache/$filename': typeof _tsrStaticServerFnCacheFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRoute
  '/lessons': typeof LessonsRoute
  '/media': typeof MediaRoute
  '/api/email': typeof ApiEmailRoute
  '/__tsr/staticServerFnCache/$filename': typeof _tsrStaticServerFnCacheFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/engagements'
    | '/lessons'
    | '/media'
    | '/api/email'
    | '/__tsr/staticServerFnCache/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/engagements'
    | '/lessons'
    | '/media'
    | '/api/email'
    | '/__tsr/staticServerFnCache/$filename'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/engagements'
    | '/lessons'
    | '/media'
    | '/api/email'
    | '/__tsr/staticServerFnCache/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EngagementsRoute: typeof EngagementsRoute
  LessonsRoute: typeof LessonsRoute
  MediaRoute: typeof MediaRoute
  ApiEmailRoute: typeof ApiEmailRoute
  _tsrStaticServerFnCacheFilenameRoute: typeof _tsrStaticServerFnCacheFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email': {
      id: '/api/email'
      path: '/api/email'
      fullPath: '/api/email'
      preLoaderRoute: typeof ApiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__tsr/staticServerFnCache/$filename': {
      id: '/__tsr/staticServerFnCache/$filename'
      path: '/__tsr/staticServerFnCache/$filename'
      fullPath: '/__tsr/staticServerFnCache/$filename'
      preLoaderRoute: typeof _tsrStaticServerFnCacheFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EngagementsRoute: EngagementsRoute,
  LessonsRoute: LessonsRoute,
  MediaRoute: MediaRoute,
  ApiEmailRoute: ApiEmailRoute,
  _tsrStaticServerFnCacheFilenameRoute: _tsrStaticServerFnCacheFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
