/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AreyouRouteImport } from './routes/areyou'
import { Route as FamilytreeRouteImport } from './routes/familytree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AreyouRoute = AreyouRouteImport.update({
  id: '/areyou',
  path: '/areyou',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilytreeRoute = FamilytreeRouteImport.update({
  id: '/familytree',
  path: '/familytree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/areyou': typeof AreyouRoute
  '/familytree': typeof FamilytreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/areyou': typeof AreyouRoute
  '/familytree': typeof FamilytreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/areyou': typeof AreyouRoute
  '/familytree': typeof FamilytreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/404' | '/areyou' | '/familytree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/404' | '/areyou' | '/familytree'
  id: '__root__' | '/' | '/404' | '/areyou' | '/familytree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AreyouRoute: typeof AreyouRoute
  FamilytreeRoute: typeof FamilytreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areyou': {
      id: '/areyou'
      path: '/areyou'
      fullPath: '/areyou'
      preLoaderRoute: typeof AreyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familytree': {
      id: '/familytree'
      path: '/familytree'
      fullPath: '/familytree'
      preLoaderRoute: typeof FamilytreeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AreyouRoute: AreyouRoute,
  FamilytreeRoute: FamilytreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
