import {readFileSync,existsSync,realpathSync,writeFileSync}from'node:fs';import{dirname,join}from'node:path';import{execFileSync}from'node:child_process';
const base=process.argv[2]??process.cwd();
const roots=[...(process.argv[2]?[]:['.']),'apps/sarabeth-studio','apps/portfolio-website','apps/carolyn-portfolio','apps/diloreto-website','apps/carolyn-portfolio/infra'];
const evidence:any={};
function resolve(from:string,dep:string):string|undefined{let p=from;for(;;){const f=join(p,'node_modules',dep,'package.json');if(existsSync(f))return realpathSync(f);const up=dirname(p);if(up===p)return;p=up;}}
for(const root of roots){let edges:any[]=[],violations:any[]=[],missing:any[]=[];const visited=new Set<string>();
function walk(file:string){file=realpathSync(file);if(visited.has(file))return;visited.add(file);const m=JSON.parse(readFileSync(file,'utf8'));for(const[type,optional]of [['dependencies',false],['optionalDependencies',true],['peerDependencies',false]] as const){for(const[dep,range]of Object.entries(m[type]??{}) as [string,string][]){let r=range;if(r.startsWith('npm:'))r=r.slice(r.lastIndexOf('@')+1);if(/^(workspace:|file:|git|https?:)/.test(r))continue;const found=resolve(dirname(file),dep);if(!found){if(!optional&&!m.peerDependenciesMeta?.[dep]?.optional)missing.push({parent:m.name,version:m.version,type,dep,range});continue;}const actual=JSON.parse(readFileSync(found,'utf8'));const edge={parent:m.name,version:m.version,type,dep,range,resolved:actual.version};edges.push(edge);try{if(!Bun.semver.satisfies(actual.version,r))violations.push(edge);}catch{}if(type!=='peerDependencies')walk(found);}}}
const path=join(base,root,'package.json');
const app=existsSync(path)?JSON.parse(readFileSync(path,'utf8')):JSON.parse(execFileSync('git',['show',JSON.parse(readFileSync('docs/migration/source-imports.json','utf8')).sources.find((s:any)=>s.name==='carolyn-portfolio').importCommit+':apps/carolyn-portfolio/infra/package.json'],{encoding:'utf8'}));for(const dep of Object.keys({...app.dependencies,...app.devDependencies})){const f=resolve(join(base,root),dep);if(f){const a=JSON.parse(readFileSync(f,'utf8'));const req={parent:app.name,type:'direct',dep,range:app.dependencies?.[dep]??app.devDependencies[dep],resolved:a.version};edges.push(req);if(!Bun.semver.satisfies(a.version,req.range))violations.push(req);walk(f);}}
evidence[root]={packages:visited.size,edgesChecked:edges.length,peerAndDirectEdges:edges.filter(e=>e.type==='direct'||e.type==='peerDependencies'),violations,missing};console.log(root,visited.size,'edges',edges.length,'violations',violations.length,'missing',missing.length);}
writeFileSync(process.argv[3]??'docs/migration/dependency-range-and-peer-evidence.json',JSON.stringify(evidence,null,2)+'\n');

if(Object.values(evidence).some((r:any)=>r.violations.length||r.missing.length))process.exitCode=1;
